---
configuration_directory: "%{cwd}/spec/unit/infra/root"
state_file: "%{cwd}/state/root.tfstate"
vars:
  region: "%{hiera('region')}"

  deployment_identifier: "%{hiera('deployment_identifier')}"

  policy_name: "test-policy-%{hiera('deployment_identifier')}"
  policy_description: "Policy for test-policy-%{hiera('deployment_identifier')}"
